*** Variables ***
## Data
${type_email}    Email
${email}        automationtester1395@gmail.com
${password}     Welcome123

## Locator
${btn_login_email}    com.todoist:id/btn_welcome_continue_with_email
${email_edit_text}    //android.widget.FrameLayout//android.widget.EditText
${btn_continue_with_mail}      com.todoist:id/btn_continue_with_email
${password_edit_text}     com.todoist:id/log_in_password
${btn_login}    com.todoist:id/btn_log_in

